class CreateVolunteers < ActiveRecord::Migration[6.0]
  def change
    create_table :volunteers do |t|
      t.integer :project_id
      t.string :first_name
      t.string :last_name
      t.string :bio
      t.string :email
      t.string :phone_number
      t.string :job_title
      t.string :employer
      t.string :linkedin_url
      t.integer :front_end
      t.integer :back_end
      t.integer :databases
      t.integer :mobile
      t.integer :dev_ops
      t.integer :wordpress
      t.integer :squarespace
      t.integer :wix
      t.integer :weebly
      t.integer :html_css
      t.integer :javascript
      t.integer :react
      t.integer :vue
      t.integer :angular
      t.integer :node_js
      t.integer :laravel
      t.integer :rails
      t.integer :django
      t.integer :asp_net
      t.integer :java
      t.integer :postgres
      t.integer :my_sql
      t.integer :sql_server
      t.integer :no_sql
      t.integer :android
      t.integer :ios
      t.integer :xamarin
      t.integer :ionic
      t.integer :react_native
      t.integer :aws
      t.integer :azure
      t.integer :heroku
      t.integer :digital_ocean
      t.integer :google_cloud_platform
      t.integer :docker
      t.integer :version_control
      t.integer :print_design
      t.integer :ux
      t.integer :ui
      t.integer :illustration
      t.integer :branding
      t.integer :motion_graphics
      t.integer :photoshop
      t.integer :illustrator
      t.integer :in_design
      t.integer :after_effects
      t.integer :sketch
      t.integer :figma
      t.integer :zeplin
      t.integer :invision
      t.integer :marvel
      t.integer :adobe_xd
      t.integer :project_management
      t.integer :brand_strategy
      t.integer :copywriting
      t.integer :crm_tools
      t.integer :marketing
      t.integer :seo
      t.integer :social_media
      t.integer :technical_writing
      t.integer :user_testing
      t.integer :photography
      t.integer :videography
    end
  end
end
